/Users/wpf/Desktop/log/test/linux-2.6.9/sound/oss/cs4281/cs4281m.c

static int mixer_ioctl(struct cs4281_state *s, unsigned int cmd,
{
get_user(val, (unsigned long __user *) argp))
get_user(val, (unsigned long __user *) argp))
get_user(val, (unsigned long __user *) argp))
get_user(val, (unsigned long __user *) argp))
get_user(val, (unsigned long __user *) argp))
get_user(val, (int __user *) argp))
get_user(val, (int __user *)argp))
get_user(val, (int __user *)argp))
get_user(val, (int __user *)argp))
get_user(val, (int __user *)argp))
get_user(val, (int __user *)argp))
get_user(val, (int __user *)argp))
get_user(val, (int __user *)argp))
get_user(val, (int __user *)argp))
get_user(val, (int __user *)argp))
get_user(val, (int __user *)argp))
get_user(val, (int __user *)argp))
get_user(val, (int __user *)argp))
get_user(val, (int __user *)argp))
get_user(val, (int __user *)argp))
get_user(val, (int __user *)argp))
get_user(val, (int __user *)argp))
get_user(val, (int __user *)argp))
get_user(val, (int __user *)argp))
get_user(val, (int __user *)argp))
get_user(val, (int __user *)argp))
get_user(val, (int __user *)argp))
get_user(val, (int __user *)argp))
get_user(val, (int __user *)argp))
get_user(val, (int __user *)argp))
get_user(val, (int __user *)argp))
get_user(val, (int __user *)argp))
get_user(val, (int __user *)argp))
get_user(val, (int __user *)argp))
get_user(val, (int __user *)argp))
get_user(val, (int __user *)argp))
get_user(val, (int __user *)argp))
get_user(val, (int __user *)argp))
get_user(val, (int __user *)argp))
get_user(val, (int __user *)argp))
get_user(val, (int __user *)argp))
get_user(val, (int __user *)argp))
get_user(val, (int __user *)argp))
get_user(val, (int __user *)argp))
get_user(val, (int __user *)argp))
get_user(val, (int __user *)argp))
get_user(val, (int __user *)argp))
get_user(val, (int __user *)argp))
get_user(val, (int __user *)argp))
get_user(val, (int __user *)argp))
get_user(val, (int __user *)argp))
get_user(val, (int __user *)argp))
get_user(val, (int __user *)argp))
get_user(val, (int __user *)argp))
get_user(val, (int __user *)argp))
get_user(val, (int __user *)argp))
get_user(val, (int __user *)argp))
get_user(val, (int __user *)argp))
get_user(val, (int __user *)argp))
}
static int cs4281_ioctl(struct inode *inode, struct file *file,
{
get_user(val, p))
get_user(val, p))
get_user(val, p))
get_user(val, p))
get_user(val, p))
get_user(val, p))
get_user(val, p))
get_user(val, p))
get_user(val, p))
get_user(val, p))
get_user(val, p))
get_user(val, p))
get_user(val, p))
get_user(val, p))
get_user(val, p))
get_user(val, p))
get_user(val, p))
get_user(val, p))
get_user(val, p))
get_user(val, p))
get_user(val, p))
get_user(val, p))
get_user(val, p))
get_user(val, p))
get_user(val, p))
get_user(val, p))
get_user(val, p))
}
