/Users/wpf/Desktop/log/test/linux-2.6.9/sound/oss/rme96xx.c

static int rme96xx_ioctl(struct inode *in, struct file *file, unsigned int cmd, unsigned long arg)
{
get_user(val, p))
get_user(val, p))
get_user(val, p))
get_user(val, p))
get_user(val, p))
get_user(val, p))
get_user(val, p))
get_user(val, p))
get_user(val, p))
get_user(val, p))
get_user(val, p))
get_user(val, p))
get_user(val, p))
get_user(val, p))
get_user(val, p))
get_user(val, p))
get_user(val, p))
get_user(val, p))
get_user(val, p))
get_user(val, p))
get_user(val, p))
get_user(val, p))
get_user(val, p))
get_user(val, p))
get_user(val, p))
get_user(val, p))
get_user(val, p))
}
static int rme96xx_mixer_ioctl(struct inode *inode, struct file *file, unsigned int cmd, unsigned long arg)
{
copy_from_user(&mixer,argp,sizeof(mixer)))
copy_from_user(&control,argp,sizeof(control)))
}
