/Users/wpf/Desktop/log/test/linux-2.6.9/sound/oss/sequencer.c

int sequencer_ioctl(int dev, struct file *file, unsigned int cmd, void __user *arg)
{
get_user(val, p))
get_user(dev, p))
get_user(dev, p))
get_user(dev, p))
get_user(val, p))
get_user(val, p))
get_user(dev, p))
get_user(dev, p))
get_user(dev, p))
get_user(val, p))
get_user(val, p))
get_user(dev, p))
get_user(dev, p))
get_user(val, p))
get_user(val, p))
get_user(dev, p))
get_user(val, p))
get_user(val, p))
get_user(dev, &((struct synth_info __user *)arg)->device))
get_user(dev, &((struct synth_info __user *)arg)->device))
get_user(val, p))
get_user(val, p))
}
