/Users/wpf/Desktop/log/test/linux-2.6.9/sound/oss/swarm_cs4297a.c

static int mixer_ioctl(struct cs4297a_state *s, unsigned int cmd,
{
get_user(val, (unsigned long *) arg))
get_user(val, (unsigned long *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
}
static int cs4297a_ioctl(struct inode *inode, struct file *file,
{
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
get_user(val, (int *) arg))
}
