/Users/wpf/Desktop/log/test/linux-2.6.9/drivers/media/video/zr36120.c

int zoran_ioctl(struct video_device* dev, unsigned int cmd, void *arg)
{
copy_from_user(&v, arg,sizeof(v)))
copy_from_user(&v, arg,sizeof(v)))
copy_from_user(&v, arg,sizeof(v)))
copy_from_user(&v, arg, sizeof(v)))
copy_from_user(&p, arg,sizeof(p)))
copy_from_user(&v, arg,sizeof(v)))
copy_from_user(&v, arg, sizeof(v)))
copy_from_user(&v, arg,sizeof(v)))
copy_from_user(&v, arg,sizeof(v)))
copy_from_user(&v, arg, sizeof(v)))
copy_from_user(&p, arg,sizeof(p)))
copy_from_user(&v, arg,sizeof(v)))
copy_from_user(&v, arg, sizeof(v)))
copy_from_user(&v, arg,sizeof(v)))
copy_from_user(&v, arg, sizeof(v)))
copy_from_user(&p, arg,sizeof(p)))
copy_from_user(&v, arg,sizeof(v)))
copy_from_user(&v, arg, sizeof(v)))
copy_from_user(&v, arg, sizeof(v)))
copy_from_user(&p, arg,sizeof(p)))
copy_from_user(&v, arg,sizeof(v)))
copy_from_user(&v, arg, sizeof(v)))
copy_from_user(&p, arg,sizeof(p)))
copy_from_user(&v, arg,sizeof(v)))
copy_from_user(&v, arg, sizeof(v)))
copy_from_user(&vw,arg,sizeof(vw)))
copy_from_user(&vm,arg,sizeof(vm)))
get_user(v, (int *)arg))
get_user(i, (int *) arg))
copy_from_user(&v, arg,sizeof(v)))
copy_from_user(&v, arg, sizeof(v)))
}
