/Users/wpf/Desktop/log/test/linux-2.6.9/fs/ncpfs/ioctl.c

int ncp_ioctl(struct inode *inode, struct file *filp,
{
copy_from_user(&request, argp, sizeof(request)))
copy_from_user(&sr, argp, sizeof(sr)))
copy_from_user(&sign, argp, sizeof(sign)))
copy_from_user(&rqdata, argp, sizeof(rqdata)))
copy_from_user(&user, argp, sizeof(user)))
copy_from_user(&user, argp, sizeof(user)))
copy_from_user(&user, argp, sizeof(user)))
copy_from_user(&user, argp, sizeof(user)))
copy_from_user(&user, argp, sizeof(user)))
copy_from_user(&sr, argp, sizeof(sr)))
copy_from_user(&sign, argp, sizeof(sign)))
copy_from_user(&rqdata, argp, sizeof(rqdata)))
copy_from_user(&user, argp, sizeof(user)))
copy_from_user(&user, argp, sizeof(user)))
copy_from_user(&user, argp, sizeof(user)))
copy_from_user(&user, argp, sizeof(user)))
copy_from_user(&user, argp, sizeof(user)))
copy_from_user(&sign, argp, sizeof(sign)))
copy_from_user(&rqdata, argp, sizeof(rqdata)))
copy_from_user(&user, argp, sizeof(user)))
copy_from_user(&user, argp, sizeof(user)))
copy_from_user(&user, argp, sizeof(user)))
copy_from_user(&user, argp, sizeof(user)))
copy_from_user(&user, argp, sizeof(user)))
copy_from_user(&rqdata, argp, sizeof(rqdata)))
copy_from_user(&user, argp, sizeof(user)))
copy_from_user(&user, argp, sizeof(user)))
copy_from_user(&user, argp, sizeof(user)))
copy_from_user(&user, argp, sizeof(user)))
copy_from_user(&user, argp, sizeof(user)))
copy_from_user(&user, argp, sizeof(user)))
copy_from_user(&user, argp, sizeof(user)))
copy_from_user(&user, argp, sizeof(user)))
copy_from_user(&user, argp, sizeof(user)))
copy_from_user(&user, argp, sizeof(user)))
copy_from_user(&user, argp, sizeof(user)))
copy_from_user(&user, argp, sizeof(user)))
copy_from_user(&user, argp, sizeof(user)))
copy_from_user(&user, argp, sizeof(user)))
copy_from_user(&user, argp, sizeof(user)))
copy_from_user(&user, argp, sizeof(user)))
copy_from_user(&user, argp, sizeof(user)))
copy_from_user(&user, argp, sizeof(user)))
copy_from_user(&user, argp, sizeof(user)))
}
